const Problem = require('./problem')

const description = `
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
`

/* eslint-disable no-constant-condition */
const problem2 = new Problem(2, description, () => {
  const fibonacci = [1, 2]
  let newNumber
  while (true) {
    newNumber = fibonacci[fibonacci.length - 1] + fibonacci[fibonacci.length - 2]
    if (newNumber < 4000000) {
      fibonacci.push(newNumber)
    } else {
      break
    }
  }
  return fibonacci.filter(x => x % 2 === 0).reduce((a, b) => a + b)
})
/* eslint-enable no-constant-condition */
module.exports = problem2
